In [17]:
# importamos librerias pandas 

import pandas as pd

import numpy as np

In [ ]:
# Cargamos el data set 

df = pd.read_csv("cars.csv")

In [15]:
# mostrar las primeras filas

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body- style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak- rpm,city-mpg,highway-mpg,price,km_per_1
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500,8.928000
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500,8.077714
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950,10.203428
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450,7.652571
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,8.5,110,5500,19,25,15250,8.077714

In [ ]:
# print the last rows of the data set 

df.tail()

In [ ]:
# Cantidad de filas y columnas 

df.shape

In [ ]:
# mostrar estadisticas de la tabla 

df.describe()

In [ ]:
# despliega informacion 

df.info()

In [ ]:
# add indentification to the columns in the data set 
# first create a list estructure whit the columns name 

headcolumns = ["symboling", "normalized-losses", "maked", "fuel-type", "aspiration", "num-of-doors", "body-style", ""]

encabezados = ["symboling","normalized-losses","make","fuel-type","aspiration","num-of-doors","body- style", "drive-wheels","engine-location","wheel-base","length","width","height","curb-weight","engine-type", "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower", "peak- rpm","city-mpg","highway-mpg","price"]

df.columns = encabezados

In [ ]:
# validamos que esten los nombres de las comillas

df.columns

In [12]:
# remplazar el simbolo de "?"

df.replace("?", np.NaN)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body- style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak- rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [14]:
# convertir millas por galon a kilometros por litro 

df['km_per_1'] = (df['city-mpg'] * 1.60934) / 3.78541

In [24]:
# convertir millas por galon a kilometros por litro para la columna higway-mpg

df['km_per_1:_highway'] = (df['highway-mpg'] * 1.60934) / 3.78541

In [ ]:
# grafica de pastel 

df["city-mpg"].mean()

In [ ]:
# grafica de pastel 

df["city-mpg"].mode()

In [ ]:
# grafica de pastel 

df["city-mpg"].std()

In [25]:
# grafica de pastel 

df["make"].value_counts().plot(kind="pie", figsize=(8,8))

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.