In [2]:
# Importar bibliotecas necesarias
import pandas as pd

In [3]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt


# Load the CSV file into a DataFrame
df = pd.read_csv('dengue_abierto.csv')

# Display the first few rows of the DataFrame to understand its structure
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,SEXO,EDAD_ANOS,ENTIDAD_RES,MUNICIPIO_RES,HABLA_LENGUA_INDIG,INDIGENA,ENTIDAD_UM_NOTIF,MUNICIPIO_UM_NOTIF,...,INMUNOSUPR,CIRROSIS_HEPATICA,EMBARAZO,DEFUNCION,DICTAMEN,TOMA_MUESTRA,RESULTADO_PCR,ESTATUS_CASO,ENTIDAD_ASIG,MUNICIPIO_ASIG
0,2024-02-19,1304867,1,11,30,48,2,2,30,48,...,2,2,2,2,5.0,2,5,1,30,48
1,2024-02-19,1304870,2,12,25,12,2,2,25,12,...,2,2,2,2,5.0,1,5,2,25,12
2,2024-02-19,1304893,1,24,23,4,2,2,23,4,...,2,2,2,2,5.0,2,5,1,23,4
3,2024-02-19,1304896,2,38,30,206,2,2,30,206,...,2,2,2,2,5.0,1,5,1,30,206
4,2024-02-19,1304928,2,4,31,90,2,1,31,90,...,2,2,2,2,5.0,2,5,1,31,90

In [4]:
# 1. Cargar el conjunto de datos en un Pandas DataFrame
df = pd.read_csv('dengue_abierto.csv')

In [5]:
# 2. Revisar las primeras filas del DataFrame
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,SEXO,EDAD_ANOS,ENTIDAD_RES,MUNICIPIO_RES,HABLA_LENGUA_INDIG,INDIGENA,ENTIDAD_UM_NOTIF,MUNICIPIO_UM_NOTIF,...,INMUNOSUPR,CIRROSIS_HEPATICA,EMBARAZO,DEFUNCION,DICTAMEN,TOMA_MUESTRA,RESULTADO_PCR,ESTATUS_CASO,ENTIDAD_ASIG,MUNICIPIO_ASIG
0,2024-02-19,1304867,1,11,30,48,2,2,30,48,...,2,2,2,2,5.0,2,5,1,30,48
1,2024-02-19,1304870,2,12,25,12,2,2,25,12,...,2,2,2,2,5.0,1,5,2,25,12
2,2024-02-19,1304893,1,24,23,4,2,2,23,4,...,2,2,2,2,5.0,2,5,1,23,4
3,2024-02-19,1304896,2,38,30,206,2,2,30,206,...,2,2,2,2,5.0,1,5,1,30,206
4,2024-02-19,1304928,2,4,31,90,2,1,31,90,...,2,2,2,2,5.0,2,5,1,31,90

In [6]:
# 3. Verificar y manejar los datos faltantes si es necesario
df.isnull().sum()
# Manejar los datos faltantes segÃºn sea necesario, por ejemplo, utilizando df.dropna() o df.fillna().

FECHA_ACTUALIZACION       0
ID_REGISTRO               0
SEXO                      0
EDAD_ANOS                 0
ENTIDAD_RES               0
MUNICIPIO_RES             0
HABLA_LENGUA_INDIG        0
INDIGENA                  0
ENTIDAD_UM_NOTIF          0
MUNICIPIO_UM_NOTIF        0
INSTITUCION_UM_NOTIF      0
FECHA_SIGN_SINTOMAS       0
TIPO_PACIENTE             0
HEMORRAGICOS              0
DIABETES                  0
HIPERTENSION              0
ENFERMEDAD_ULC_PEPTICA    0
ENFERMEDAD_RENAL          0
INMUNOSUPR                0
CIRROSIS_HEPATICA         0
EMBARAZO                  0
DEFUNCION                 0
DICTAMEN                  1
TOMA_MUESTRA              0
RESULTADO_PCR             0
ESTATUS_CASO              0
ENTIDAD_ASIG              0
MUNICIPIO_ASIG            0
dtype: int64

In [7]:
# 4. Obtener informaciÃ³n estadÃ­stica bÃ¡sica sobre variables numÃ©ricas
df.describe()

,ID_REGISTRO,SEXO,EDAD_ANOS,ENTIDAD_RES,MUNICIPIO_RES,HABLA_LENGUA_INDIG,INDIGENA,ENTIDAD_UM_NOTIF,MUNICIPIO_UM_NOTIF,INSTITUCION_UM_NOTIF,...,INMUNOSUPR,CIRROSIS_HEPATICA,EMBARAZO,DEFUNCION,DICTAMEN,TOMA_MUESTRA,RESULTADO_PCR,ESTATUS_CASO,ENTIDAD_ASIG,MUNICIPIO_ASIG
count,2.656100e+04,26561.000000,26561.00000,26561.000000,26561.000000,26561.000000,26561.000000,26561.000000,26561.000000,26561.000000,...,26561.000000,26561.000000,26561.000000,26561.000000,26560.000000,26561.000000,26561.000000,26561.000000,26561.000000,26561.000000
mean,1.315828e+06,1.474380,26.36275,17.076691,31.168518,1.989910,1.987689,17.075713,33.040209,7.409096,...,1.998343,1.999322,1.987237,1.997101,4.996875,1.501412,4.823990,1.564098,17.241105,32.789729
std,8.243057e+03,0.499353,17.31796,8.058724,62.437649,0.099943,0.110273,8.065406,81.466430,5.207085,...,0.040668,0.026024,0.112253,0.053765,0.060353,0.500007,0.628519,0.777970,8.802690,75.169210
min,1.299508e+06,1.000000,0.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.308845e+06,1.000000,12.00000,12.000000,2.000000,2.000000,2.000000,12.000000,2.000000,4.000000,...,2.000000,2.000000,2.000000,2.000000,5.000000,1.000000,5.000000,1.000000,12.000000,2.000000
50%,1.315957e+06,1.000000,23.00000,14.000000,7.000000,2.000000,2.000000,14.000000,6.000000,4.000000,...,2.000000,2.000000,2.000000,2.000000,5.000000,2.000000,5.000000,1.000000,14.000000,6.000000
75%,1.322932e+06,2.000000,38.00000,23.000000,38.000000,2.000000,2.000000,23.000000,38.000000,12.000000,...,2.000000,2.000000,2.000000,2.000000,5.000000,2.000000,5.000000,2.000000,23.000000,38.000000
max,1.329959e+06,2.000000,110.00000,35.000000,570.000000,2.000000,2.000000,32.000000,999.000000,99.000000,...,2.000000,2.000000,2.000000,2.000000,5.000000,2.000000,5.000000,3.000000,99.000000,999.000000

In [8]:
# 5. Identificar las variables categÃ³ricas en el conjunto de datos
categoricas = df.select_dtypes(include=['object']).columns
print(categoricas)

Index(['FECHA_ACTUALIZACION', 'FECHA_SIGN_SINTOMAS'], dtype='object')

In [10]:
# 6. Obtener las medidas de tendencia central para variables numÃ©ricas
columnas_numericas = df.select_dtypes(include=['int64', 'float64']).columns

media = df[columnas_numericas].mean()
moda = df[columnas_numericas].mode().iloc[0]
desviacion_estandar = df[columnas_numericas].std()

print("Media:\n", media)
print("\nModa:\n", moda)
print("\nDesviaciÃ³n EstÃ¡ndar:\n", desviacion_estandar)

Media:
 ID_REGISTRO               1.315828e+06
SEXO                      1.474380e+00
EDAD_ANOS                 2.636275e+01
ENTIDAD_RES               1.707669e+01
MUNICIPIO_RES             3.116852e+01
HABLA_LENGUA_INDIG        1.989910e+00
INDIGENA                  1.987689e+00
ENTIDAD_UM_NOTIF          1.707571e+01
MUNICIPIO_UM_NOTIF        3.304021e+01
INSTITUCION_UM_NOTIF      7.409096e+00
TIPO_PACIENTE             1.207033e+00
HEMORRAGICOS              1.992094e+00
DIABETES                  1.978992e+00
HIPERTENSION              1.986597e+00
ENFERMEDAD_ULC_PEPTICA    1.999511e+00
ENFERMEDAD_RENAL          1.997515e+00
INMUNOSUPR                1.998343e+00
CIRROSIS_HEPATICA         1.999322e+00
EMBARAZO                  1.987237e+00
DEFUNCION                 1.997101e+00
DICTAMEN                  4.996875e+00
TOMA_MUESTRA              1.501412e+00
RESULTADO_PCR             4.823990e+00
ESTATUS_CASO              1.564098e+00
ENTIDAD_ASIG              1.724111e+01
MUNICIPIO_ASIG            3.278973e+01
dtype: float64

Moda:
 ID_REGISTRO               1299508.0
SEXO                            1.0
EDAD_ANOS                      12.0
ENTIDAD_RES                    12.0
MUNICIPIO_RES                   1.0
HABLA_LENGUA_INDIG              2.0
INDIGENA                        2.0
ENTIDAD_UM_NOTIF               12.0
MUNICIPIO_UM_NOTIF              1.0
INSTITUCION_UM_NOTIF            4.0
TIPO_PACIENTE                   1.0
HEMORRAGICOS                    2.0
DIABETES                        2.0
HIPERTENSION                    2.0
ENFERMEDAD_ULC_PEPTICA          2.0
ENFERMEDAD_RENAL                2.0
INMUNOSUPR                      2.0
CIRROSIS_HEPATICA               2.0
EMBARAZO                        2.0
DEFUNCION                       2.0
DICTAMEN                        5.0
TOMA_MUESTRA                    2.0
RESULTADO_PCR                   5.0
ESTATUS_CASO                    1.0
ENTIDAD_ASIG                   12.0
MUNICIPIO_ASIG                  1.0
Name: 0, dtype: float64

DesviaciÃ³n EstÃ¡ndar:
 ID_REGISTRO               8243.056804
SEXO                         0.499353
EDAD_ANOS                   17.317960
ENTIDAD_RES                  8.058724
MUNICIPIO_RES               62.437649
HABLA_LENGUA_INDIG           0.099943
INDIGENA                     0.110273
ENTIDAD_UM_NOTIF             8.065406
MUNICIPIO_UM_NOTIF          81.466430
INSTITUCION_UM_NOTIF         5.207085
TIPO_PACIENTE                0.405187
HEMORRAGICOS                 0.088567
DIABETES                     0.143414
HIPERTENSION                 0.114995
ENFERMEDAD_ULC_PEPTICA       0.022118
ENFERMEDAD_RENAL             0.049787
INMUNOSUPR                   0.040668
CIRROSIS_HEPATICA            0.026024
EMBARAZO                     0.112253
DEFUNCION                    0.053765
DICTAMEN                     0.060353
TOMA_MUESTRA                 0.500007
RESULTADO_PCR                0.628519
ESTATUS_CASO                 0.777970
ENTIDAD_ASIG                 8.802690
MUNICIPIO_ASIG              75.169210
dtype: float64

In [11]:
# 7. Contar el nÃºmero de casos por categorÃ­a para cada variable categÃ³rica
for columna in categoricas:
    print(f"\nNÃºmero de casos por categorÃ­a en {columna}:\n", df[columna].value_counts())

NÃºmero de casos por categorÃ­a en FECHA_ACTUALIZACION:
 FECHA_ACTUALIZACION
2024-02-19    26561
Name: count, dtype: int64

NÃºmero de casos por categorÃ­a en FECHA_SIGN_SINTOMAS:
 FECHA_SIGN_SINTOMAS
2024-01-15    835
2024-01-21    775
2024-01-22    769
2024-01-20    760
2024-01-08    750
2024-01-14    735
2024-01-29    707
2024-01-28    691
2024-01-16    685
2024-01-01    669
2024-01-07    660
2024-01-19    660
2024-01-12    648
2024-01-06    646
2024-01-23    641
2024-01-13    639
2024-01-09    631
2024-01-10    623
2024-01-18    615
2024-01-05    604
2024-01-11    598
2024-01-26    589
2024-01-30    585
2024-01-24    578
2024-01-27    577
2024-01-02    565
2024-01-17    561
2024-01-03    558
2024-02-10    558
2024-01-25    552
2024-02-06    551
2024-01-04    548
2024-02-05    546
2024-02-07    503
2024-02-12    494
2024-02-04    476
2024-01-31    474
2024-02-03    474
2024-02-11    466
2024-02-09    458
2024-02-02    456
2024-02-08    452
2024-02-01    442
2024-02-13    341
2024-02-14    265
2024-02-15    119
2024-02-16     26
2024-02-17      6
Name: count, dtype: int64

In [4]:
# Obtain the number of cases of classic dengue and dengue hemorrhagic fever
classic_dengue_cases = df[df['Dengue_Type'] == 'Classic']['Number_of_Cases'].sum()
hemorrhagic_fever_cases = df[df['Dengue_Type'] == 'Hemorrhagic']['Number_of_Cases'].sum()

classic_dengue_cases, hemorrhagic_fever_cases

KeyError: 'Dengue_Type'

In [1]:
# 9. Obtener el nÃºmero de pacientes fallecidos por tipo de dengue y categorÃ­a de edad
fallecidos_por_tipo_edad = df.groupby(['tipo_dengue', 'edad_cat'])['fallecido'].sum()
print("\nNÃºmero de pacientes fallecidos por tipo de dengue y categorÃ­a de edad:\n", fallecidos_por_tipo_edad)

NameError: name 'df' is not defined

In [2]:
# 10. Visualizar la distribuciÃ³n de casos de dengue por categorÃ­a utilizando grÃ¡ficos de barras
plt.figure(figsize=(10, 6))
sns.countplot(x='categoria', data=df)
plt.title('DistribuciÃ³n de casos de Dengue por CategorÃ­a')
plt.show()

NameError: name 'plt' is not defined